# Generated by Django 3.1.7 on 2021-03-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210304_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='todo_list_id',
            new_name='todo_list',
        ),
    ]
